### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np


array([0.39893266, 0.52465545, 0.62983417, 0.55148533, 0.71223438,
       0.22467875, 0.50033136, 0.49524731, 0.35557354, 0.10789856])

In [5]:
vec = np.random.uniform(0, 1, 10)
print('Vector:\n', vec)
print('Shape:', vec.shape)

Vector:
 [0.17845441 0.25528383 0.6319149  0.56954265 0.08915106 0.93699726
 0.53611426 0.7756119  0.13673694 0.1104347 ]
Shape: (10,)


In [4]:
matrix = np.array([[11,14,17],
                   [20,23,26],
                   [29,32,25]])
print('Matrix:\n', matrix)
print('Shape:', matrix.shape)

Matrix:
 [[11 14 17]
 [20 23 26]
 [29 32 25]]
Shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [7]:
print('Vector + 10:\n', (vec + 10).round(2))

Vector + 10:
 [10.18 10.26 10.63 10.57 10.09 10.94 10.54 10.78 10.14 10.11]


In [ ]:
print("Matrix *2:\n", matrix * 2)

Matrix *2:
 [[22 28 34]
 [40 46 52]
 [58 64 50]]


In [17]:
vec_2 = vec**2
print('Vector squared:\n', vec_2)

Vector squared:
 [0.03184598 0.06516983 0.39931644 0.32437883 0.00794791 0.87796387
 0.2874185  0.60157382 0.01869699 0.01219582]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)


array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

[[0.17 0.38]
 [0.58 0.11]
 [0.75 0.15]]


In [ ]:
print(B.T)

[[0.17 0.38]
 [0.58 0.11]
 [0.75 0.15]]


In [25]:
B_T = B.T
result_matrix = np.dot(A, B_T)
print('Result of A dot B:\n', result_matrix)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [18]:
result_matrix = np.dot(B, C)
print('Result of B dot C:\n', result_matrix)

ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.


